
const express = require('express')
const wikiRoutes = express()
const router = express.Router()
const  addPage  = require("../views/addPage")

router.get('/', (req, res, next) => {
    res.send("get working")
    next()
})

router.post('/', (req, res, next) => {
    res.send("post working")
    next()
})

router.get('/add', (req, res, next) => {
    
    //send the addpage html generated by the /views/addpage module
    res.send(addPage())
    //next()
})


module.exports = router